### PR TITLE
Make lyric view default view

### PR DESCRIPTION
**Pull request by brandonxia01**

### CODE REVIEW

**Comment by brotatotes** [comment]
Would be surprised if this didn't break some tests.

**Review by brotatotes — APPROVED** [review]
Ok w me, but wonder if this could be annoying for some users as the lyric/music view pref is not saved across reloads.

**Comment by brandonxia01** [comment]
>

**Comment by brandonxia01** [comment]
woops.

**Comment by brandonxia01** [comment]
> Ok w me, but wonder if this could be annoying for some users as the lyric/music view pref is not saved across reloads.

Possibly. I think it is better this way by default, we can add the settings preference also

**Review by brotatotes — APPROVED** [review]

**Pull request merged**
