### PR TITLE
Derzan/theme toggle

### PR DESCRIPTION
**Pull request by MiTo0o**

### CODE REVIEW

**Comment by MiTo0o** [comment]
1. Default to local storage for theme preference
2. Try to use system preferences for theme if local preference not found
3. If local preference not found and the browser doesn't support [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), it will default to light mode.

**Comment by MiTo0o** [comment]
image
image

**Comment by MiTo0o** [comment]
closes #125

**Comment by MiTo0o** [comment]
image
just realized that this part can be simplified to something like this....
```js
const toggle = Object.values(document.body.classList).indexOf("dark") > -1 ? "light" : "dark";
window.localStorage.setItem("theme", toggle);
```
would this be better?

**Review by brandonxia01 — COMMENTED** [review]
This is dope! Couple of comments, but overall looks awesome!

**Review by brandonxia01 — APPROVED** [review]
Looks good to me!

**Pull request merged**
