### PR TITLE
Introduce lazy loading in the list view

### PR DESCRIPTION
**Pull request by brotatotes**
- lazily load the list of songs using IonInfiniteScroll. We will only ever load 10-20 songs at a time. Should further improve performance.
- Revert to previous behavior: if no search terms entered, display full list of songs (lazily).

### CODE REVIEW

**Comment by brotatotes** [comment]
This PR breaks searching by number. Will fix and update later.

**Review by brandonxia01 — COMMENTED** [review]
This is sweet, loading the list works well on my phone 🏎️🔥🔥🔥

Ik you said search by number broke but it might be a little too broken haha it just crashes the code and shows a white screen if I type a number on the pre-release apk, haven't tried on web yet

**Comment by brotatotes** [comment]
Yeah it's very broken. I will need to fix in this same PR.

**Comment by brotatotes** [comment]
Number search should be working now.

**Review by brandonxia01 — APPROVED** [review]
Awesome!

**Pull request merged**
