### PR TITLE
User feedback now automatically creates a GitHub issue in this repo

### LINKED ISSUE #107: Automate User Feedback.
Instead of sending an email, maybe feedback should automatically create an issue in this repo. That's what I've been finding myself doing manually with each piece of feedback anyway.

### PR DESCRIPTION
**Pull request by MiTo0o**
Closes #107 

Changes
- Made providing name optional for feedback
- Using a dummy account to create github issues
- Added subject/title field to the feedback form
- Removed EmailJS

TODO
- add tests
- use @octokit/rest for smaller bundle size?
- npm uninstall emailJS
- issues are created by [https://github.com/Bobby-the-Builder](https://github.com/Bobby-the-Builder) currently. Eric said it's too troll, what should the name and profile pic be?

Question/Concerns
- what happens if sensitive info is sent?  We could tell them that their feedback will be public?
- Need to add some filtering for spam? (example. get all open issues and if content is the same as any of them, we don't create a new one)
- do we still want emailJS? maybe to send email when an issue is created? But the .then() and .catch() chain looks ugly since we aren't doing async await. it woud be something like `createIssue().catch(error => console.error(error)).then(email.send().catch(error => console.error(error)).then(updateFeedBackForm()))`

### CODE REVIEW

**Review by brandonxia01 — COMMENTED** [review]
Thanks for adding this! My thoughts on your todos/questions:

1. add tests - Not blocking, only if it's easy. Usually features that require internet access have to be mocked, which makes it not that valuable of a test. If you want, you can add a "create real github ticket test" which actually does try to make a ticket, and then keep it as `it.skip(..)` when we go to merge it.

2. use @octokit/rest for smaller bundle size? - w/e works, what's the difference?

3. npm uninstall emailJS - yes go for it. Somewhat related - when making this PR did you `npm install` fresh off of `master`? Im wondering if the big diff in package-lock can be avoided in this PR. No worries if it actually was needed.

4. issues are created by https://github.com/Bobby-the-Builder currently. Eric said it's too troll, what should the name and profile pic be? - Maybe we can rename the bot to something like `Hymnal-Feedback`? Profile pic can be the leaf logo?


Question/Concerns

1. what happens if sensitive info is sent? We could tell them that their feedback will be public? - I think this is probably ok. It's feedback for an app so they shouldnt care who it goes to.

2. Need to add some filtering for spam? (example. get all open issues and if content is the same as any of them, we don't create a new one) - We could rate limit ppl to only creating issues every X seconds based on some local storage property, but thats not foolproof. Can you create a github issue add rate limiting to submitting feedback? No need to implement it in this PR.

3. do we still want emailJS? maybe to send email when an issue is created? But the .then() and .catch() chain looks ugly since we aren't doing async await. it woud be something like createIssue().catch(error => console.error(error)).then(email.send().catch(error => console.error(error)).then(updateFeedBackForm())) - Nah, let's get rid of emailJS. It served its purpose, but this is better.

**Comment by MiTo0o** [comment]
> 1. add tests - Not blocking, only if it's easy. Usually features that require internet access have to be mocked, which makes it not that valuable of a test. If you want, you can add a "create real github ticket test" which actually does try to make a ticket, and then keep it as `it.skip(..)` when we go to merge it.
> 2. use @octokit/rest for smaller bundle size? - w/e works, what's the difference?
> 3. npm uninstall emailJS - yes go for it. Somewhat related - when making this PR did you `npm install` fresh off of `master`? Im wondering if the big diff in package-lock can be avoided in this PR. No worries if it actually was needed.
> 4. issues are created by https://github.com/Bobby-the-Builder currently. Eric said it's too troll, what should the name and profile pic be? - Maybe we can rename the bot to something like `Hymnal-Feedback`? Profile pic can be the leaf logo?
1. Probably just gonna not test this feature for now. As you said, it's kind of hard to create a good test for this. People can just test it by running the dev app build and submitting feedback manually. 
2. Octokit contains everything (grapql, rest, and some other stuff). Since we only need to use the rest api, I think using `@Octokit/rest` is better cuz its much smaller. Here's the bundle phobia comparison. [Octokit](https://bundlephobia.com/package/octokit@1.7.1) vs [@Octokit/rest](https://bundlephobia.com/package/@octokit/rest@18.12.0)
3. I did `npm install`  a while ago when I worked on some other stuff so I don't remember. Not sure why the `package-lock.json` got sooo much added. I tried to delete `package-lock.json` and run `npm install` again but it just started failing github action tests. I'm just not gonna mess with `package-lock.json` since I have no idea how it works.
4. changed name and profile pic to suggested.

**Comment by brotatotes** [comment]
New issue creator: https://github.com/Hymnal-Feedback

**Review by brotatotes — APPROVED** [review]
lgtm

**Pull request merged**
